# Generated by Django 2.2.12 on 2020-08-23 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('url', models.URLField(blank=True)),
                ('image', models.ImageField(null=True, upload_to='tutorials/')),
                ('summary', models.TextField(blank=True, default='')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorials.Topic')),
            ],
        ),
    ]
