# Generated by Django 2.2.12 on 2020-09-08 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0004_auto_20200907_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='lang',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French')], max_length=2),
        ),
    ]
