# Generated by Django 2.2.12 on 2020-10-21 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0005_auto_20200908_0355'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='type',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
