# Generated by Django 2.2.12 on 2020-10-24 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0006_tutorial_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/topics/'),
        ),
        migrations.AddField(
            model_name='topic',
            name='summary',
            field=models.TextField(blank=True, default=''),
        ),
    ]
